variables:
  DOCKER_DRIVER: overlay2
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  PORT: 9308

stages:
  - lint
  - build

services:
  - docker:dind

.tags-template: &tags-definition
  tags:
    - ix-ai

pylint:
  <<: *tags-definition
  image: python:latest
  stage: lint
  script:
    - curl -o .pylintrc https://tool.ix.ai/.pylintrc
    - pip install prometheus_client pylint stellar-base mnemonic toml pygelf
    - pylint --rcfile=.pylintrc src/*.py

build:
  <<: *tags-definition
  image: docker:latest
  stage: build
  only:
    - /^latest$/
    - tags
    - /(.*)-dev$/
  script:
    - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}
    - docker build -f Dockerfile -t ${IMAGE_TAG} --build-arg PORT="${PORT}" .
    - docker push ${IMAGE_TAG}
